### ISSUE TITLE
Use alternate white/black colors

### ISSUE THREAD

**Issue by LemonBoy** [fcpg/vim-fahrenheit#1]
The xterm palette provides true black (#000) and true white (#fff) in slot `16` and `231` respectively, it'd be nice to use those instead of `0` and `15` since those fall into the user-customizable range and make the colorscheme look different depending on the palette.
The same goes for vim-orbital.

**Comment by fcpg** [comment]
Done for Fahrenheit.  Will do it for Orbital in a few days if there's no issue.
