### ISSUE TITLE
In readme.md: wrong install line for vim-plug

### ISSUE THREAD

**Issue by rollingthedice** [fcpg/vim-fahrenheit#4]
The readme line to install with vim-plug is incorrect.
Under "Installation", readme.md says: Plug - `Plug 'fcpg/vim-complimentary'`
But it should be: Plug - `Plug 'fcpg/vim-fahrenheit'`

**Comment by fcpg** [comment]
Ah, thanks for reporting it!

**Comment by rollingthedice** [comment]
Thanks for fixing, love this theme :D
